credentials:
  usernames:
    johndoe:
      name: Christophe Brichet
      password: abc  # Hashed password for 'password1'
    janesmith:
      name: Miguel Pecqueux
      password: def  # Hashed password for 'password2'
cookie:
  expiry_days: 1
  key: support
  name: app-support
preauthorized: []
